version: '3'
services:
  web:
    image: odoo:latest
    depends_on:
      - soluci0ndb
    ports:
      - "8069:8069"
    environment:
    - HOST=soluci0ndb
    - USER=odoo
    - PASSWORD=soluci-ON
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./odoo/config:/etc/odoo
      - ./odoo/addons:/mnt/extra-addons
  soluci0ndb:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=soluci-ON
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
volumes:
  odoo-web-data:
  odoo-db-data:
